
import { Perfume, ScentFamily } from './types';

export const featuredPerfumes: Perfume[] = [
  // Floral
  {
    name: 'No. 5',
    brand: 'Chanel',
    description: 'The iconic, timeless floral-aldehyde fragrance, a symbol of elegant femininity. A complex bouquet built around May rose and jasmine.',
    topNotes: ['Aldehydes', 'Ylang-Ylang', 'Neroli', 'Bergamot'],
    middleNotes: ['Iris', 'Jasmine', 'Rose', 'Lily-of-the-Valley'],
    baseNotes: ['Sandalwood', 'Vetiver', 'Amber', 'Musk'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.1.jpg',
    family: 'Floral',
    longevity: 4,
    sillage: 4,
    likes: 489,
    dislikes: 52,
    isVerified: true,
    amazonSearchTerm: 'Chanel No 5 Eau de Parfum',
    affiliate: { provider: 'amazon', tag: 'chanelbeauty-21' },
    reviews: [
        { author: 'ClassicGal', rating: 5, comment: 'An absolute masterpiece. It makes me feel so elegant and timeless. Not for everyone, but iconic for a reason.', date: '2023-10-15' },
        { author: 'ScentExplorer', rating: 4, comment: 'The aldehydes are very strong at first, but the dry down is a beautiful powdery floral. A must-try for any collector.', date: '2023-09-22' },
    ]
  },
  {
    name: "J'adore",
    brand: 'Dior',
    description: 'A grand floral fragrance that balances sensuous curves and vibrant fruit notes. It celebrates the essence of ylang-ylang and Damascus rose.',
    topNotes: ['Ylang-Ylang', 'Pear', 'Melon', 'Peach'],
    middleNotes: ['Jasmine', 'Damascus Rose', 'Tuberose', 'Freesia'],
    baseNotes: ['Musk', 'Vanilla', 'Cedar', 'Blackberry'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.2.jpg',
    family: 'Floral',
    longevity: 5,
    sillage: 4,
    likes: 832,
    dislikes: 31,
    isVerified: true,
    amazonSearchTerm: 'Dior J\'adore Eau de Parfum',
    affiliate: { provider: 'amazon', tag: 'diorfragrance-21' },
    reviews: [
        { author: 'LilyPetals', rating: 5, comment: 'This is my signature scent! It\'s so feminine, classy, and versatile. I get compliments every time I wear it.', date: '2023-11-01' },
    ],
    clones: [
        { brand: 'Zara', name: 'Wonder Rose' },
        { brand: 'Maison Alhambra', name: 'Jardin De Paris' },
    ]
  },
  // Oriental
  {
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    description: 'An addictive gourmand floral with a shot of adrenaline-rich coffee. It is a vibrant, sensual and addictive contrast of light and dark.',
    topNotes: ['Pink Pepper', 'Orange Blossom', 'Pear'],
    middleNotes: ['Coffee', 'Jasmine', 'Almond', 'Licorice'],
    baseNotes: ['Vanilla', 'Patchouli', 'Cedar', 'Cashmere Wood'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.25324.jpg',
    family: 'Oriental',
    longevity: 5,
    sillage: 5,
    likes: 1205,
    dislikes: 88,
    isVerified: false,
    amazonSearchTerm: 'Yves Saint Laurent Black Opium',
    reviews: [
        { author: 'NightOwl', rating: 5, comment: 'The coffee and vanilla combination is intoxicating. Perfect for a night out. It\'s sexy, dark, and sweet all at once.', date: '2023-10-28' },
        { author: 'GourmandLover', rating: 4, comment: 'Very sweet but the coffee note gives it a nice edge. Lasts forever on my skin.', date: '2023-09-10' },
    ],
    clones: [
        { brand: 'Lovali', name: 'Black Addiction' },
    ]
  },
  {
    name: 'Shalimar',
    brand: 'Guerlain',
    description: 'A legendary fragrance with a sensual, spellbinding amber and vanilla trail. Inspired by the passionate love story between an emperor and an Indian princess.',
    topNotes: ['Bergamot', 'Lemon', 'Mandarin Orange'],
    middleNotes: ['Iris', 'Jasmine', 'Rose', 'Patchouli'],
    baseNotes: ['Vanilla', 'Tonka Bean', 'Incense', 'Sandalwood'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.10.jpg',
    family: 'Oriental',
    longevity: 5,
    sillage: 4,
    likes: 642,
    dislikes: 75,
    isVerified: true,
    amazonSearchTerm: 'Guerlain Shalimar Eau de Parfum',
    reviews: [
        { author: 'VintageVibes', rating: 5, comment: 'Shalimar is a legend. The smoky vanilla and citrus opening is pure magic. It feels like wearing a piece of history.', date: '2023-08-19' },
    ]
  },
  // Woody
  {
    name: 'Santal 33',
    brand: 'Le Labo',
    description: 'An iconic woody aromatic that captures the spirit of the American West. A defining image of the spirit of the American West and its personal freedom.',
    topNotes: ['Violet Accord', 'Cardamom'],
    middleNotes: ['Iris', 'Ambrox'],
    baseNotes: ['Sandalwood', 'Cedarwood', 'Leather', 'Papyrus'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.12201.jpg',
    family: 'Woody',
    longevity: 5,
    sillage: 5,
    likes: 1530,
    dislikes: 110,
    isVerified: false,
    amazonSearchTerm: 'Le Labo Santal 33',
    reviews: [
        { author: 'HikerChic', rating: 5, comment: 'Smells like a cozy, sophisticated campfire. The sandalwood and leather are incredible. It\'s unique and instantly recognizable.', date: '2023-10-05' },
    ],
    clones: [
      { brand: 'Le Monde Gourmand', name: 'Santal Supreme' },
    ]
  },
  {
    name: "Terre d'Hermès",
    brand: 'Hermès',
    description: 'A narrative of earth and sky, blending mineral flint with vibrant citrus and spices. The scent of earth, lying on your back, eyes to the heavens.',
    topNotes: ['Orange', 'Grapefruit'],
    middleNotes: ['Pepper', 'Pelargonium', 'Flint'],
    baseNotes: ['Vetiver', 'Cedar', 'Patchouli', 'Benzoin'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.17.jpg',
    family: 'Woody',
    longevity: 4,
    sillage: 3,
    likes: 980,
    dislikes: 40,
    isVerified: true,
    amazonSearchTerm: 'Hermès Terre d\'Hermès',
    reviews: [
        { author: 'MrGentleman', rating: 5, comment: 'The perfect masculine scent. Earthy, citrusy, and incredibly classy. It is my go-to for the office and special occasions.', date: '2023-11-02' },
    ],
    clones: [
        { brand: 'Armaf', name: 'Eternia Man' },
        { brand: 'Rasasi', name: 'Fattan' },
        { brand: 'Maison Alhambra', name: 'Toro by Maison Alhambra' },
    ]
  },
  // Citrus
  {
    name: 'Light Blue',
    brand: 'Dolce & Gabbana',
    description: 'A fresh, fruity-floral scent that evokes the spirit of a Sicilian summer. A tribute to the scorching sun, the sea, and the sensuality of the Mediterranean.',
    topNotes: ['Sicilian Lemon', 'Apple', 'Cedar', 'Bellflower'],
    middleNotes: ['Bamboo', 'Jasmine', 'White Rose'],
    baseNotes: ['Cedar', 'Musk', 'Amber'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.41.jpg',
    family: 'Citrus',
    longevity: 3,
    sillage: 3,
    likes: 789,
    dislikes: 25,
    isVerified: false,
    amazonSearchTerm: 'Dolce & Gabbana Light Blue',
    reviews: [
        { author: 'SummerBreeze', rating: 4, comment: 'The ultimate summer fragrance. It\'s so fresh and clean. Doesn\'t last very long on me, but I love reapplying it throughout the day.', date: '2023-07-20' },
    ],
    clones: [
        { brand: 'La Ree Fragrances', name: 'Shades of Blue' },
        { brand: 'Lattafa', name: '24k White Gold' },
        { brand: 'Santalys', name: 'Invocation' },
    ]
  },
  {
    name: 'Colonia',
    brand: 'Acqua di Parma',
    description: 'The quintessential Italian scent, a timeless blend of Sicilian citrus and aromatic herbs. A fresh, refined, and timeless fragrance for a pragmatic and successful man.',
    topNotes: ['Lemon', 'Sweet Orange', 'Calabrian Bergamot'],
    middleNotes: ['Lavender', 'Bulgarian Rose', 'Verbena', 'Rosemary'],
    baseNotes: ['Vetiver', 'Sandalwood', 'Patchouli'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.1292.jpg',
    family: 'Citrus',
    longevity: 3,
    sillage: 2,
    likes: 550,
    dislikes: 18,
    isVerified: true,
    amazonSearchTerm: 'Acqua di Parma Colonia',
    reviews: [
        { author: 'ItalianStyle', rating: 5, comment: 'Pure class in a bottle. A beautiful, natural-smelling citrus cologne that never goes out of style.', date: '2023-06-15' },
    ]
  },
  // Fresh
  {
    name: 'Acqua di Giò',
    brand: 'Giorgio Armani',
    description: 'A scent of freedom, full of wind and water, capturing Mediterranean freshness. A perfect harmony of sweet and salty notes of sea water and nuances of sunny warmth.',
    topNotes: ['Lime', 'Lemon', 'Bergamot', 'Jasmine'],
    middleNotes: ['Sea Notes', 'Calone', 'Peach', 'Freesia'],
    baseNotes: ['White Musk', 'Cedar', 'Oakmoss', 'Patchouli'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.22.jpg',
    family: 'Fresh',
    longevity: 4,
    sillage: 3,
    likes: 1890,
    dislikes: 65,
    isVerified: true,
    amazonSearchTerm: 'Giorgio Armani Acqua di Giò',
    reviews: [
         { author: 'OceanLover', rating: 5, comment: 'This IS the smell of the ocean. So refreshing and clean. It has been a classic for decades for a good reason.', date: '2023-08-01' },
    ],
    clones: [
      { brand: 'Perry Ellis', name: '360 Red' },
      { brand: 'Frank Olivier', name: 'Blue Touch' },
      { brand: 'Armaf', name: 'Blur Homme' },
      { brand: 'Ajmal', name: 'Shiro' },
    ]
  },
  {
    name: 'CK One',
    brand: 'Calvin Klein',
    description: 'The revolutionary first unisex fragrance, clean, modern, and universally appealing. A balance between brightness and sensuality.',
    topNotes: ['Lemon', 'Green Notes', 'Bergamot', 'Pineapple'],
    middleNotes: ['Nutmeg', 'Violet', 'Orris Root', 'Jasmine'],
    baseNotes: ['Sandalwood', 'Amber', 'Musk', 'Cedar'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.199.jpg',
    family: 'Fresh',
    longevity: 3,
    sillage: 2,
    likes: 995,
    dislikes: 45,
    isVerified: false,
    amazonSearchTerm: 'Calvin Klein CK One',
    reviews: [
        { author: '90sKid', rating: 4, comment: 'Takes me right back to my youth! Still a great, easy-to-wear scent for any day. It\'s just so clean and effortless.', date: '2023-09-05' },
    ]
  },
  // Spicy
  {
    name: 'Spicebomb',
    brand: 'Viktor&Rolf',
    description: 'An explosive concentrate of masculine sensuality with a mix of spices, leather, and tobacco. An instant olfactory detonation.',
    topNotes: ['Pink Pepper', 'Elemi', 'Bergamot', 'Grapefruit'],
    middleNotes: ['Cinnamon', 'Saffron', 'Paprika'],
    baseNotes: ['Tobacco', 'Leather', 'Vetiver'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.13221.jpg',
    family: 'Spicy',
    longevity: 5,
    sillage: 4,
    likes: 1340,
    dislikes: 92,
    isVerified: false,
    amazonSearchTerm: 'Viktor&Rolf Spicebomb',
    reviews: [
        { author: 'WinterWarmth', rating: 5, comment: 'The perfect winter fragrance. It\'s warm, spicy, and so cozy. The cinnamon and tobacco are incredible together.', date: '2023-11-05' },
    ],
    clones: [
      { brand: 'Remy Latour', name: 'Signature Night Armaf' },
      { brand: 'Cremo', name: 'Spice & Black Vanilla', notes: 'Inspired by Spicebomb Extreme' },
      { brand: 'Bulgari', name: 'Man in Black', notes: 'Inspired by Spicebomb Extreme' },
    ]
  },
  {
    name: 'Tobacco Vanille',
    brand: 'Tom Ford',
    description: 'A lavish, warm, and iconic fragrance featuring opulent tobacco, vanilla, and spice. Reminiscent of an English Gentleman’s Club.',
    topNotes: ['Tobacco Leaf', 'Spicy Notes'],
    middleNotes: ['Vanilla', 'Cacao', 'Tonka Bean', 'Tobacco Blossom'],
    baseNotes: ['Dried Fruits', 'Woody Notes'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.1825.jpg',
    family: 'Spicy',
    longevity: 5,
    sillage: 5,
    likes: 2150,
    dislikes: 120,
    isVerified: true,
    amazonSearchTerm: 'Tom Ford Tobacco Vanille',
    reviews: [
        { author: 'LuxuryScents', rating: 5, comment: 'Pure opulence. The tobacco is rich and realistic, and the vanilla is creamy and divine. Worth every penny for its performance and quality.', date: '2023-10-20' },
    ],
    clones: [
        { brand: 'Maison Alhambra', name: 'Tobacco Touch' },
        { brand: 'Al Haramain', name: 'Amber Oud Tobacco Edition' },
    ]
  },
  {
    name: 'Attraction Potion',
    brand: 'Scent Seduction',
    description: 'A revolutionary fragrance engineered with synthetic pheromones designed to enhance your natural allure and create an irresistible magnetic aura. A subtle yet powerful statement.',
    topNotes: ['Iso E Super', 'Pink Pepper'],
    middleNotes: ['Hedione', 'Iris', 'Ambroxan'],
    baseNotes: ['White Musk', 'Cashmeran', 'Vetiver'],
    family: 'Woody',
    longevity: 5,
    sillage: 4,
    likes: 1987,
    dislikes: 155,
    isVerified: false,
    amazonSearchTerm: 'Pheromone Perfume for Attraction',
    reviews: [
        { author: 'DateNightDarling', rating: 5, comment: 'I was skeptical, but wow! I wore this out and the compliments were non-stop. It feels like it amplifies my own scent in the best way possible. Definitely a confidence booster!', date: '2023-11-10' },
        { author: 'TheAlchemist', rating: 4, comment: 'The concept is fascinating. It\'s a very clean, "your-skin-but-better" scent. Whether it\'s the pheromones or just a great composition, it\'s undeniably intriguing and gets noticed.', date: '2023-10-18' },
    ],
    clones: []
  },
  {
    name: 'Accento Overdose Pride Edition',
    brand: 'Xerjoff',
    description: 'An explosion of colour and confidence, this intensely rich and radiant fragrance celebrates freedom and inclusion with fruity, green top notes, a fresh heart of eucalyptus, and an alluring base of jasmine and rose.',
    topNotes: ['Fruity Notes', 'Aldehydes', 'Green Notes'],
    middleNotes: ['Bulgarian Rose', 'Egyptian Jasmine', 'Lily-of-the-Valley'],
    baseNotes: ['Eucalyptus', 'Pine'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/o.74630.jpg',
    family: 'Floral Green',
    longevity: 1,
    sillage: 1,
    likes: 29,
    dislikes: 261,
    isVerified: false,
    amazonSearchTerm: 'Accento Overdose Pride Edition Xerjoff',
    reviews: [
        { author: 'ckorp8', rating: 4, comment: 'I bought this for its bottle which looks very lovely indeed. The scent, however, really leaves a lot to be desired. After a long while the rose finally appeared with some sweet accompanying note. Then the overall scent became much better, upping it to a like.', date: '2024-02-10' },
        { author: 'Jezur', rating: 1, comment: 'Genuinely thought this was reviewbombed by a bunch of homophobes but wow... Nasty stuff, Xerjoff. Be better.', date: '2024-07-02' },
    ]
  },
  {
    name: 'Classique Pride 2024',
    brand: 'Jean Paul Gaultier',
    description: 'A perfume with the colors of the rainbow that loudly and strongly proclaims self-love and love for differences. A floral fragrance with fresh citrus, neroli, and a soft woody musk base.',
    topNotes: ['Yuzu', 'Citruses'],
    middleNotes: ['Neroli', 'Orange Blossom'],
    baseNotes: ['Blonde Woods', 'Musk'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/o.90394.jpg',
    family: 'Floral',
    longevity: 2,
    sillage: 2,
    likes: 40,
    dislikes: 104,
    isVerified: false,
    amazonSearchTerm: 'Jean Paul Gaultier Classique Pride 2024',
    reviews: [
        { author: 'peachsiie', rating: 3, comment: "Strong citrusy lemon zest, sweet neroli blossoms, and a very clean musk with something green hidden at the bottom. it’s a bit too floral for my tastes but on someone else this would probably smell great in summer, very refreshing.", date: '2025-04-19' },
    ]
  },
  {
    name: 'Pride Edition Man',
    brand: 'Bruno Banani',
    description: 'A Woody Aromatic fragrance for men, with a fruity and nutty character. Launched in 2019 to celebrate pride.',
    topNotes: ['Guarana', 'Red Apple', 'Grapefruit'],
    middleNotes: ['Guava', 'Walnut', 'Lavender'],
    baseNotes: ['Vetiver', 'Benzoin', 'Amber'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/o.55514.jpg',
    family: 'Woody Aromatic',
    longevity: 2,
    sillage: 2,
    likes: 25,
    dislikes: 58,
    isVerified: false,
    amazonSearchTerm: 'Bruno Banani Pride Edition Man',
    reviews: []
  },
  {
    name: 'Classique Pride 2023',
    brand: 'Jean Paul Gaultier',
    description: 'A unisex fragrance celebrating pride, created by Natalie Gracia-Cetto and Quentin Bisch. A vibrant citrus opening meets a heart of neroli and orange blossom, grounded by musk and white woods.',
    topNotes: ['Blood Orange', 'Yuzu'],
    middleNotes: ['Neroli', 'Orange Blossom'],
    baseNotes: ['Musk', 'White Woods'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/o.81775.jpg',
    family: 'Citrus Aromatic',
    longevity: 2,
    sillage: 2,
    likes: 100,
    dislikes: 270,
    isVerified: false,
    amazonSearchTerm: 'Jean Paul Gaultier Classique Pride 2023',
    reviews: [
        { author: 'queensizefun', rating: 5, comment: "I don't know why this fragrance gets tremendous hate. God, it's amazing. It is a soft powdery Citrus with vanilla. The Citrus is so real upon first spray. It makes me want to keep spraying but don't! Because it is going to last all day long.", date: '2024-04-28' },
    ]
  },
  {
    name: 'Unstopp Man',
    brand: 'Feromon',
    description: 'A powerful and unstoppable fragrance for the modern man.',
    topNotes: ['Bergamot', 'Grapefruit'],
    middleNotes: ['Pepper', 'Lavender'],
    baseNotes: ['Vetiver', 'Patchouli'],
    imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75878.jpg',
    family: 'Woody Spicy',
    longevity: 4,
    sillage: 4,
    likes: 120,
    dislikes: 10,
    isVerified: false,
    reviews: []
  },
  {
      name: 'Target Woman',
      brand: 'Feromon',
      description: 'A captivating scent that hits the mark every time.',
      topNotes: ['Red Berries', 'Mandarin'],
      middleNotes: ['Jasmine', 'Rose'],
      baseNotes: ['Vanilla', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75879.jpg',
      family: 'Floral Fruity',
      longevity: 3,
      sillage: 3,
      likes: 95,
      dislikes: 8,
      isVerified: false,
      reviews: []
  },
  {
      name: 'The First One',
      brand: 'United Hits',
      description: 'A classic and memorable fragrance for men.',
      topNotes: ['Citrus', 'Apple'],
      middleNotes: ['Cinnamon', 'Clove'],
      baseNotes: ['Sandalwood', 'Cedar'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75876.jpg',
      family: 'Woody Spicy',
      longevity: 4,
      sillage: 3,
      likes: 88,
      dislikes: 12,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Potere Pour Homme',
      brand: 'Potere',
      description: 'A scent that embodies power and sophistication.',
      topNotes: ['Lemon', 'Mint'],
      middleNotes: ['Geranium', 'Rosemary'],
      baseNotes: ['Tonka Bean', 'Amber'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75875.jpg',
      family: 'Aromatic',
      longevity: 5,
      sillage: 4,
      likes: 150,
      dislikes: 5,
      isVerified: false,
      reviews: []
  },
  {
      name: 'The Only Way Pour Homme',
      brand: 'The Only Way',
      description: 'The definitive fragrance for the decisive man.',
      topNotes: ['Bergamot', 'Pepper'],
      middleNotes: ['Lavender', 'Sichuan Pepper'],
      baseNotes: ['Ambroxan', 'Cedar'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75873.jpg',
      family: 'Aromatic Fougere',
      longevity: 4,
      sillage: 4,
      likes: 135,
      dislikes: 9,
      isVerified: false,
      reviews: []
  },
  {
      name: 'En Liesse Pour Homme',
      brand: 'En Liesse',
      description: 'A joyful and uplifting scent for everyday wear.',
      topNotes: ['Mandarin', 'Neroli'],
      middleNotes: ['Sea Salt', 'Grapefruit'],
      baseNotes: ['Cedarwood', 'Amber'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75872.jpg',
      family: 'Citrus Aromatic',
      longevity: 3,
      sillage: 3,
      likes: 70,
      dislikes: 4,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Piano',
      brand: 'Bon Chant',
      description: 'A harmonious composition of notes creating a melodic scent.',
      topNotes: ['Pear', 'Black Currant'],
      middleNotes: ['Iris', 'Jasmine'],
      baseNotes: ['Patchouli', 'Praline'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75871.jpg',
      family: 'Floral Fruity Gourmand',
      longevity: 4,
      sillage: 3,
      likes: 110,
      dislikes: 15,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Eveille Les Sentiments Pour Femme',
      brand: 'Eveille Les Sentiments',
      description: 'Awaken the senses with this delicate and romantic fragrance.',
      topNotes: ['Peony', 'Litchi'],
      middleNotes: ['Rose', 'Magnolia'],
      baseNotes: ['Cedar', 'Amber'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75870.jpg',
      family: 'Floral',
      longevity: 3,
      sillage: 3,
      likes: 85,
      dislikes: 6,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Deep Sea',
      brand: 'Old Spice',
      description: 'A fresh, aquatic scent reminiscent of the open ocean.',
      topNotes: ['Sea Notes', 'Citrus'],
      middleNotes: ['Spices', 'Floral Notes'],
      baseNotes: ['Amber', 'Woody Notes'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75868.jpg',
      family: 'Aromatic Aquatic',
      longevity: 3,
      sillage: 2,
      likes: 200,
      dislikes: 25,
      isVerified: true,
      reviews: []
  },
  {
      name: 'L\'or Rouge',
      brand: 'L\'eau & Cassis',
      description: 'A rich and luxurious fragrance with a hint of red.',
      topNotes: ['Cassis', 'Blackberry'],
      middleNotes: ['Rose', 'Peony'],
      baseNotes: ['Musk', 'Patchouli'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75867.jpg',
      family: 'Fruity Floral',
      longevity: 4,
      sillage: 3,
      likes: 90,
      dislikes: 11,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Irth Gold',
      brand: 'Nabeel',
      description: 'An opulent and golden fragrance inspired by the treasures of the earth.',
      topNotes: ['Saffron', 'Raspberry'],
      middleNotes: ['Oud', 'Rose'],
      baseNotes: ['Amber', 'Incense'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75866.jpg',
      family: 'Oriental Woody',
      longevity: 5,
      sillage: 5,
      likes: 180,
      dislikes: 14,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Janan Platinum',
      brand: 'J.',
      description: 'A modern and sophisticated scent with a platinum touch.',
      topNotes: ['Apple', 'Bergamot'],
      middleNotes: ['Plum', 'Orange Blossom'],
      baseNotes: ['Amber', 'Sandalwood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75865.jpg',
      family: 'Fruity',
      longevity: 4,
      sillage: 4,
      likes: 210,
      dislikes: 18,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Hajne Blue',
      brand: 'J.',
      description: 'A fresh and invigorating scent inspired by the endless blue sky.',
      topNotes: ['Marine notes', 'Bergamot'],
      middleNotes: ['Lavender', 'Geranium'],
      baseNotes: ['Musk', 'Ambergris'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75864.jpg',
      family: 'Aromatic Aquatic',
      longevity: 4,
      sillage: 3,
      likes: 140,
      dislikes: 12,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Hajne Brown',
      brand: 'J.',
      description: 'A warm and earthy fragrance with a rugged character.',
      topNotes: ['Cardamom', 'Nutmeg'],
      middleNotes: ['Leather', 'Sandalwood'],
      baseNotes: ['Amber', 'Tonka Bean'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75863.jpg',
      family: 'Leather',
      longevity: 5,
      sillage: 4,
      likes: 165,
      dislikes: 9,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Hajne Black',
      brand: 'J.',
      description: 'A dark, mysterious, and seductive fragrance for the night.',
      topNotes: ['Black Pepper', 'Incense'],
      middleNotes: ['Oud', 'Patchouli'],
      baseNotes: ['Labdanum', 'Benzoin'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75862.jpg',
      family: 'Oriental Woody',
      longevity: 5,
      sillage: 5,
      likes: 195,
      dislikes: 20,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Hajne Gold',
      brand: 'J.',
      description: 'A luxurious and opulent scent that shines bright.',
      topNotes: ['Saffron', 'Mandarin'],
      middleNotes: ['Osmanthus', 'Rose'],
      baseNotes: ['Oud', 'Vanilla'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75861.jpg',
      family: 'Oriental Floral',
      longevity: 5,
      sillage: 4,
      likes: 220,
      dislikes: 15,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Le Male Le Parfum',
      brand: 'Jean Paul Gaultier',
      description: 'An intense and elegant reinterpretation of the classic Le Male.',
      topNotes: ['Cardamom'],
      middleNotes: ['Lavender', 'Iris'],
      baseNotes: ['Vanilla', 'Oriental notes', 'Woody Notes'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.61545.jpg',
      family: 'Amber',
      longevity: 5,
      sillage: 4,
      likes: 3500,
      dislikes: 200,
      isVerified: true,
      reviews: []
  },
  {
      name: 'Imaginari',
      brand: 'Jacques Yves',
      description: 'A scent that sparks the imagination and transcends reality.',
      topNotes: ['Ginger', 'Grapefruit'],
      middleNotes: ['Ambroxan', 'Water Notes'],
      baseNotes: ['Amber', 'Labdanum'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75860.jpg',
      family: 'Aromatic Aquatic',
      longevity: 4,
      sillage: 3,
      likes: 115,
      dislikes: 7,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Nostalgia',
      brand: 'Deja Vu by Yusuf Bhai',
      description: 'A fragrance that evokes cherished memories of the past.',
      topNotes: ['Violet Leaf', 'Bergamot'],
      middleNotes: ['Iris', 'Powdery Notes'],
      baseNotes: ['Sandalwood', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75859.jpg',
      family: 'Floral Woody Musk',
      longevity: 4,
      sillage: 3,
      likes: 105,
      dislikes: 10,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Surreal',
      brand: 'Deja Vu by Yusuf Bhai',
      description: 'An otherworldly and dreamlike olfactory experience.',
      topNotes: ['Absinthe', 'Anise'],
      middleNotes: ['Fennel', 'Mint'],
      baseNotes: ['Licorice', 'Leather'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75858.jpg',
      family: 'Aromatic Green',
      longevity: 4,
      sillage: 4,
      likes: 99,
      dislikes: 13,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Arousal',
      brand: 'Deja Vu by Yusuf Bhai',
      description: 'A deeply sensual and provocative fragrance.',
      topNotes: ['Cinnamon', 'Rum'],
      middleNotes: ['Tobacco', 'Leather'],
      baseNotes: ['Vanilla', 'Oud'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75857.jpg',
      family: 'Spicy Amber',
      longevity: 5,
      sillage: 4,
      likes: 180,
      dislikes: 15,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Myth',
      brand: 'Deja Vu by Yusuf Bhai',
      description: 'A legendary scent of heroic proportions.',
      topNotes: ['Laurel', 'Grapefruit'],
      middleNotes: ['Guaiac Wood', 'Marine Accord'],
      baseNotes: ['Ambergris', 'Oakmoss'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75856.jpg',
      family: 'Woody Aquatic',
      longevity: 4,
      sillage: 4,
      likes: 155,
      dislikes: 8,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Rendezvous',
      brand: 'Deja Vu by Yusuf Bhai',
      description: 'A romantic and intimate scent for special moments.',
      topNotes: ['Champagne', 'Litchi'],
      middleNotes: ['Rose', 'Peony'],
      baseNotes: ['White Musk', 'Woody Notes'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75855.jpg',
      family: 'Floral Fruity',
      longevity: 3,
      sillage: 3,
      likes: 125,
      dislikes: 4,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Anemoia',
      brand: 'Deja Vu by Yusuf Bhai',
      description: 'A fragrance of nostalgia for a time you\'ve never known.',
      topNotes: ['Ink', 'Paper'],
      middleNotes: ['Leather', 'Violet'],
      baseNotes: ['Birch Tar', 'Cedar'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75854.jpg',
      family: 'Leather',
      longevity: 4,
      sillage: 2,
      likes: 95,
      dislikes: 18,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Memoir',
      brand: 'Deja Vu by Yusuf Bhai',
      description: 'An unforgettable story told through scent.',
      topNotes: ['Incense', 'Pepper'],
      middleNotes: ['Opoponax', 'Labdanum'],
      baseNotes: ['Myrrh', 'Sandalwood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75853.jpg',
      family: 'Amber',
      longevity: 5,
      sillage: 4,
      likes: 160,
      dislikes: 11,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Tar',
      brand: 'TAR',
      description: 'A bold, industrial, and unapologetically modern scent.',
      topNotes: ['Asphalt', 'Gasoline'],
      middleNotes: ['Leather', 'Rubber'],
      baseNotes: ['Vetiver', 'Birch Tar'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75852.jpg',
      family: 'Leather',
      longevity: 5,
      sillage: 5,
      likes: 250,
      dislikes: 50,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Pour Homme',
      brand: 'Yusuf Bhai',
      description: 'A signature masculine fragrance, timeless and elegant.',
      topNotes: ['Citrus', 'Lavender'],
      middleNotes: ['Spices', 'Herbs'],
      baseNotes: ['Woody Notes', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75851.jpg',
      family: 'Aromatic',
      longevity: 4,
      sillage: 3,
      likes: 140,
      dislikes: 9,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Midnight Rodeo',
      brand: 'by Romy',
      description: 'The scent of a moonlit night, leather, and wild freedom.',
      topNotes: ['Raspberry', 'Saffron'],
      middleNotes: ['Leather', 'Jasmine'],
      baseNotes: ['Amber', 'Suede'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75848.jpg',
      family: 'Leather',
      longevity: 5,
      sillage: 4,
      likes: 175,
      dislikes: 12,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Games Song',
      brand: 'Routine Paris',
      description: 'A playful and energetic fragrance for the winner in you.',
      topNotes: ['Mint', 'Apple'],
      middleNotes: ['Tonka Bean', 'Geranium'],
      baseNotes: ['Vanilla', 'Cedar'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75847.jpg',
      family: 'Aromatic Fougere',
      longevity: 4,
      sillage: 4,
      likes: 130,
      dislikes: 8,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Saffron Imperial',
      brand: 'Routine Paris',
      description: 'A regal and majestic scent built around precious saffron.',
      topNotes: ['Saffron', 'Raspberry'],
      middleNotes: ['Rose', 'Oud'],
      baseNotes: ['Leather', 'Amber'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75846.jpg',
      family: 'Oriental Spicy',
      longevity: 5,
      sillage: 4,
      likes: 200,
      dislikes: 14,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Harvest Bloom',
      brand: 'Routine Paris',
      description: 'The scent of a golden autumn afternoon and blooming flowers.',
      topNotes: ['Pear', 'Bergamot'],
      middleNotes: ['Tuberose', 'Jasmine'],
      baseNotes: ['Patchouli', 'Vetiver'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75845.jpg',
      family: 'Chypre Floral',
      longevity: 4,
      sillage: 3,
      likes: 115,
      dislikes: 6,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Damask Haus',
      brand: 'Damask Haus',
      description: 'An intricate and opulent fragrance, like a fine damask fabric.',
      topNotes: ['Damask Rose', 'Pink Pepper'],
      middleNotes: ['Oud', 'Praline'],
      baseNotes: ['Clove', 'Guaiac Wood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75843.jpg',
      family: 'Oriental Floral',
      longevity: 5,
      sillage: 4,
      likes: 190,
      dislikes: 11,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Whispering Kiss',
      brand: 'Le Persona Fragrance',
      description: 'A soft, intimate, and delicate whisper of a scent.',
      topNotes: ['Rice Powder', 'Ambrette'],
      middleNotes: ['Iris', 'Rose'],
      baseNotes: ['White Musk', 'Vanilla'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75842.jpg',
      family: 'Floral Woody Musk',
      longevity: 3,
      sillage: 2,
      likes: 145,
      dislikes: 5,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Sage Horizon',
      brand: 'by Romy',
      description: 'An aromatic and calming scent inspired by vast, open landscapes.',
      topNotes: ['Sage', 'Grapefruit'],
      middleNotes: ['Sea Salt', 'Ambrette'],
      baseNotes: ['Driftwood', 'Seaweed'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75841.jpg',
      family: 'Aromatic Aquatic',
      longevity: 3,
      sillage: 3,
      likes: 120,
      dislikes: 8,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Florist',
      brand: 'Ard al Teeb',
      description: 'A vibrant and realistic bouquet of freshly cut flowers.',
      topNotes: ['Green Leaves', 'Freesia'],
      middleNotes: ['Peony', 'Tuberose', 'Lily'],
      baseNotes: ['Musk', 'Powdery Notes'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75840.jpg',
      family: 'Floral Green',
      longevity: 4,
      sillage: 3,
      likes: 110,
      dislikes: 7,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Love is War',
      brand: 'B Fragrance',
      description: 'A passionate and conflicting fragrance of love\'s battles.',
      topNotes: ['Blood Orange', 'Gunpowder'],
      middleNotes: ['Rose', 'Metal'],
      baseNotes: ['Patchouli', 'Oud'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75839.jpg',
      family: 'Chypre Floral',
      longevity: 5,
      sillage: 5,
      likes: 220,
      dislikes: 25,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Shy Extreme',
      brand: 'Routine Paris',
      description: 'A surprisingly bold fragrance for the quietly confident.',
      topNotes: ['Peach', 'Bergamot'],
      middleNotes: ['Osmanthus', 'Rose'],
      baseNotes: ['Suede', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75837.jpg',
      family: 'Fruity Leather',
      longevity: 4,
      sillage: 3,
      likes: 100,
      dislikes: 10,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Fabulous Whiskey',
      brand: 'Routine Paris',
      description: 'A rich, smooth, and intoxicating scent inspired by fine whiskey.',
      topNotes: ['Whiskey', 'Spices'],
      middleNotes: ['Tonka Bean', 'Tobacco'],
      baseNotes: ['Oak', 'Vanilla'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75836.jpg',
      family: 'Amber Spicy',
      longevity: 5,
      sillage: 4,
      likes: 230,
      dislikes: 16,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Pouvoir Noir',
      brand: 'Routine Paris',
      description: 'The power of darkness, captured in a bottle.',
      topNotes: ['Incense', 'Black Pepper'],
      middleNotes: ['Oud', 'Leather'],
      baseNotes: ['Labdanum', 'Vetiver'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75835.jpg',
      family: 'Oriental Woody',
      longevity: 5,
      sillage: 5,
      likes: 190,
      dislikes: 22,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Oudh Himalayan',
      brand: 'Routine Paris',
      description: 'A spiritual and grounding scent of oud from the high mountains.',
      topNotes: ['Spices', 'Herbs'],
      middleNotes: ['Himalayan Oud', 'Cedar'],
      baseNotes: ['Sandalwood', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75834.jpg',
      family: 'Woody',
      longevity: 5,
      sillage: 4,
      likes: 180,
      dislikes: 13,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Sakura',
      brand: 'Routine Paris',
      description: 'A delicate and ethereal scent of cherry blossoms in spring.',
      topNotes: ['Cherry Blossom', 'Pear'],
      middleNotes: ['Rose', 'Jasmine'],
      baseNotes: ['Hinoki Wood', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75833.jpg',
      family: 'Floral',
      longevity: 3,
      sillage: 2,
      likes: 150,
      dislikes: 5,
      isVerified: false,
      reviews: []
  },
  {
      name: 'L\'Art de Versailles',
      brand: 'Routine Paris',
      description: 'A scent of royal gardens, opulence, and artistry.',
      topNotes: ['Bergamot', 'Galbanum'],
      middleNotes: ['Tuberose', 'Hyacinth'],
      baseNotes: ['Oakmoss', 'Amber'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75832.jpg',
      family: 'Chypre Floral',
      longevity: 4,
      sillage: 4,
      likes: 160,
      dislikes: 9,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Dangerous Love',
      brand: 'Routine Paris',
      description: 'A thrilling and addictive fragrance of forbidden romance.',
      topNotes: ['Rum', 'Passionfruit'],
      middleNotes: ['Gardenia', 'Tonka Bean'],
      baseNotes: ['Vanilla', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75831.jpg',
      family: 'Amber Vanilla',
      longevity: 5,
      sillage: 4,
      likes: 210,
      dislikes: 18,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Heaven Soleia',
      brand: 'Routine Paris',
      description: 'A bright, solar fragrance that feels like heavenly sunshine.',
      topNotes: ['Ylang-Ylang', 'Mandarin'],
      middleNotes: ['Tiare Flower', 'Jasmine'],
      baseNotes: ['Coconut Milk', 'Vanilla'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75830.jpg',
      family: 'Floral Fruity',
      longevity: 4,
      sillage: 3,
      likes: 140,
      dislikes: 7,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Forbidden',
      brand: 'Routine Paris',
      description: 'A tempting and mysterious scent that invites you to break the rules.',
      topNotes: ['Plum', 'Liqueur'],
      middleNotes: ['Turkish Rose', 'Jasmine'],
      baseNotes: ['Tonka Bean', 'Sandalwood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75829.jpg',
      family: 'Amber Floral',
      longevity: 5,
      sillage: 4,
      likes: 185,
      dislikes: 12,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Jardin Absolu',
      brand: 'Routine Paris',
      description: 'The absolute essence of a lush, vibrant garden in full bloom.',
      topNotes: ['Green Leaves', 'Hyacinth'],
      middleNotes: ['Lily-of-the-Valley', 'Jasmine'],
      baseNotes: ['Musk', 'Oakmoss'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75828.jpg',
      family: 'Floral Green',
      longevity: 4,
      sillage: 3,
      likes: 130,
      dislikes: 6,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Harmonie',
      brand: 'Routine Paris',
      description: 'A perfectly balanced and serene fragrance.',
      topNotes: ['Lavender', 'Bergamot'],
      middleNotes: ['Iris', 'Jasmine Tea'],
      baseNotes: ['Sandalwood', 'White Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75826.jpg',
      family: 'Aromatic',
      longevity: 3,
      sillage: 3,
      likes: 110,
      dislikes: 4,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Ceylon Vibe',
      brand: 'Routine Paris',
      description: 'A spicy and aromatic journey to the tea plantations of Ceylon.',
      topNotes: ['Black Tea', 'Cardamom'],
      middleNotes: ['Cinnamon', 'Ginger'],
      baseNotes: ['Woody Notes', 'Vanilla'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75825.jpg',
      family: 'Aromatic Spicy',
      longevity: 4,
      sillage: 3,
      likes: 145,
      dislikes: 8,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Forbidden Love',
      brand: 'Yusuf Bhai',
      description: 'A passionate and intense fragrance of a love that defies all odds.',
      topNotes: ['Tuberose', 'Jasmine'],
      middleNotes: ['Osmanthus', 'Rose'],
      baseNotes: ['Amber', 'Cedar'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75824.jpg',
      family: 'Floral',
      longevity: 5,
      sillage: 4,
      likes: 160,
      dislikes: 10,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Legendary',
      brand: 'Yusuf Bhai',
      description: 'A heroic and powerful scent for the modern legend.',
      topNotes: ['Pineapple', 'Bergamot'],
      middleNotes: ['Birch', 'Patchouli'],
      baseNotes: ['Musk', 'Oakmoss'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75823.jpg',
      family: 'Chypre Fruity',
      longevity: 5,
      sillage: 4,
      likes: 250,
      dislikes: 15,
      isVerified: false,
      reviews: []
  },
  {
      name: 'White Blossom',
      brand: 'Routine Paris',
      description: 'A pure and delicate scent of blooming white flowers.',
      topNotes: ['Neroli', 'Orange Blossom'],
      middleNotes: ['Jasmine', 'Gardenia'],
      baseNotes: ['Tuberose', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75821.jpg',
      family: 'White Floral',
      longevity: 4,
      sillage: 3,
      likes: 135,
      dislikes: 6,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Bonheur',
      brand: 'Routine Paris',
      description: 'The scent of pure happiness and joyful moments.',
      topNotes: ['Mandarin Orange', 'Blackcurrant'],
      middleNotes: ['Rose', 'Peony'],
      baseNotes: ['Patchouli', 'White Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75820.jpg',
      family: 'Fruity Floral',
      longevity: 3,
      sillage: 3,
      likes: 120,
      dislikes: 5,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Lapi Nou',
      brand: 'Odette Parfum Co.',
      description: 'A soft, comforting, and slightly sweet fragrance.',
      topNotes: ['Milk', 'Almond'],
      middleNotes: ['Vanilla', 'Heliotrope'],
      baseNotes: ['Musk', 'Sandalwood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75819.jpg',
      family: 'Gourmand',
      longevity: 4,
      sillage: 2,
      likes: 105,
      dislikes: 8,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Bohème',
      brand: 'Routine Paris',
      description: 'A free-spirited and unconventional artistic scent.',
      topNotes: ['Incense', 'Spices'],
      middleNotes: ['Patchouli', 'Leather'],
      baseNotes: ['Amber', 'Sandalwood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75818.jpg',
      family: 'Woody Oriental',
      longevity: 4,
      sillage: 3,
      likes: 150,
      dislikes: 12,
      isVerified: false,
      reviews: []
  },
  {
      name: 'La Vie',
      brand: 'Routine Paris',
      description: 'A celebration of life, vibrant and full of joy.',
      topNotes: ['Black Currant', 'Pear'],
      middleNotes: ['Iris', 'Jasmine', 'Orange Blossom'],
      baseNotes: ['Praline', 'Vanilla', 'Patchouli'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75817.jpg',
      family: 'Floral Fruity Gourmand',
      longevity: 5,
      sillage: 4,
      likes: 300,
      dislikes: 20,
      isVerified: false,
      reviews: []
  },
  {
      name: 'French Oud',
      brand: 'Yusuf Bhai',
      description: 'A sophisticated fusion of French perfumery and oriental oud.',
      topNotes: ['Lavender', 'Bergamot'],
      middleNotes: ['Oud', 'Rose'],
      baseNotes: ['Sandalwood', 'Patchouli'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75816.jpg',
      family: 'Oriental Fougere',
      longevity: 5,
      sillage: 4,
      likes: 190,
      dislikes: 14,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Bloody Oud',
      brand: 'Yusuf Bhai',
      description: 'A dark, intense, and dramatic interpretation of oud.',
      topNotes: ['Blood Orange', 'Spices'],
      middleNotes: ['Oud', 'Leather'],
      baseNotes: ['Amber', 'Incense'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75815.jpg',
      family: 'Oriental Woody',
      longevity: 5,
      sillage: 5,
      likes: 220,
      dislikes: 25,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Tropical Pop',
      brand: 'Nomad',
      description: 'An effervescent and juicy tropical cocktail in a bottle.',
      topNotes: ['Pineapple', 'Mango'],
      middleNotes: ['Coconut', 'Passionfruit'],
      baseNotes: ['Rum', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75813.jpg',
      family: 'Fruity',
      longevity: 3,
      sillage: 3,
      likes: 130,
      dislikes: 7,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Pacificano',
      brand: 'Yusuf Bhai',
      description: 'A cool and refreshing scent inspired by the Pacific coast.',
      topNotes: ['Sea Salt', 'Grapefruit'],
      middleNotes: ['Sage', 'Seaweed'],
      baseNotes: ['Driftwood', 'Ambrette'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75812.jpg',
      family: 'Aromatic Aquatic',
      longevity: 4,
      sillage: 3,
      likes: 140,
      dislikes: 8,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Magical Flow',
      brand: 'Yusuf Bhai',
      description: 'A whimsical and enchanting fragrance that flows with magic.',
      topNotes: ['Ozonic notes', 'Water Lily'],
      middleNotes: ['Cyclamen', 'Peony'],
      baseNotes: ['Musk', 'Sandalwood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75811.jpg',
      family: 'Floral Aquatic',
      longevity: 3,
      sillage: 3,
      likes: 110,
      dislikes: 5,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Domestic Noir',
      brand: 'Yusuf Bhai',
      description: 'A dark and intriguing scent for the modern femme or homme fatale.',
      topNotes: ['Coffee', 'Pink Pepper'],
      middleNotes: ['Orange Blossom', 'Jasmine'],
      baseNotes: ['Vanilla', 'Patchouli'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75810.jpg',
      family: 'Amber Vanilla',
      longevity: 5,
      sillage: 4,
      likes: 170,
      dislikes: 12,
      isVerified: false,
      reviews: []
  },
  {
      name: 'Modern Blossom',
      brand: 'Yusuf Bhai',
      description: 'A contemporary take on classic floral bouquets.',
      topNotes: ['Freesia', 'Litchi'],
      middleNotes: ['Magnolia', 'Pepper'],
      baseNotes: ['Amber', 'Musk'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75809.jpg',
      family: 'Floral',
      longevity: 4,
      sillage: 3,
      likes: 125,
      dislikes: 6,
      isVerified: false,
      reviews: []
  },
  {
      name: 'City Walk',
      brand: 'Yusuf Bhai',
      description: 'A vibrant and energetic scent for navigating the urban jungle.',
      topNotes: ['Grapefruit', 'Mint'],
      middleNotes: ['Ginger', 'Nutmeg'],
      baseNotes: ['Cedar', 'Sandalwood'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75808.jpg',
      family: 'Woody Spicy',
      longevity: 4,
      sillage: 3,
      likes: 130,
      dislikes: 9,
      isVerified: false,
      reviews: []
  },
  {
      name: 'XS Night Extreme',
      brand: 'Yusuf Bhai',
      description: 'An extreme and electrifying scent for unforgettable nights.',
      topNotes: ['Absinthe', 'Cinnamon'],
      middleNotes: ['Myrrh', 'Cacao'],
      baseNotes: ['Caramel', 'Patchouli'],
      imageUrl: 'https://fimgs.net/mdimg/perfume/375x500.75807.jpg',
      family: 'Amber Spicy',
      longevity: 5,
      sillage: 5,
      likes: 200,
      dislikes: 20,
      isVerified: false,
      reviews: []
  }
];

// In a real application, this data would be dynamically determined by user activity,
// review counts, or recent sales data from a backend service. For this demo,
// we'll select a few popular items to simulate a "trending" list.
const trendingPerfumeNames = ['Black Opium', 'Santal 33', 'Acqua di Giò', 'Attraction Potion'];
export const trendingPerfumes: Perfume[] = featuredPerfumes.filter(p => trendingPerfumeNames.includes(p.name));


export const scentFamilies: ScentFamily[] = [
    {
        name: "Floral",
        description: "From single blossoms to complex bouquets, floral scents are romantic and classic.",
        perfumes: featuredPerfumes.filter(p => p.family === 'Floral'),
        color: "bg-gradient-to-br from-rose-300 to-pink-400",
    },
    {
        name: "Oriental",
        description: "Rich and opulent, oriental fragrances feature notes like vanilla, spices, and resins.",
        perfumes: featuredPerfumes.filter(p => p.family === 'Oriental'),
        color: "bg-gradient-to-br from-amber-400 to-orange-500",
    },
    {
        name: "Woody",
        description: "Warm and earthy, these scents are grounded in notes of cedar, sandalwood, and vetiver.",
        perfumes: featuredPerfumes.filter(p => p.family === 'Woody'),
        color: "bg-gradient-to-br from-yellow-700 to-lime-800",
    },
    {
        name: "Citrus",
        description: "Light, zesty, and refreshing, citrus scents are perfect for vibrant, energetic moods.",
        perfumes: featuredPerfumes.filter(p => p.family === 'Citrus'),
        color: "bg-gradient-to-br from-yellow-300 to-orange-300",
    },
    {
        name: "Fresh",
        description: "Clean and invigorating, with notes of aquatic, green, or aromatic elements.",
        perfumes: featuredPerfumes.filter(p => p.family === 'Fresh'),
        color: "bg-gradient-to-br from-sky-300 to-cyan-400",
    },
    {
        name: "Spicy",
        description: "Warm and comforting, featuring notes like cinnamon, clove, and pepper.",
        perfumes: featuredPerfumes.filter(p => p.family === 'Spicy'),
        color: "bg-gradient-to-br from-red-500 to-orange-600",
    },
];

export const commonNotes: string[] = [
    "Vanilla", "Sandalwood", "Rose", "Jasmine", "Bergamot", "Cedarwood",
    "Patchouli", "Musk", "Amber", "Vetiver", "Lavender", "Lemon",
    "Orange Blossom", "Oud", "Tobacco", "Leather", "Iris", "Gardenia"
];

export const occasions: { name: string; id: 'everyday' | 'office' | 'night' | 'event' }[] = [
    { name: 'Everyday', id: 'everyday' },
    { name: 'Office', id: 'office' },
    { name: 'Date Night', id: 'night' },
    { name: 'Special Event', id: 'event' },
];
